Repository GeoffreyDlvl/IHM-Manette, pull requests merged in 2020-10, with the labels that each got.

#3 Feature/jump
  Assets/Prefabs/Ground.prefab
  Assets/Prefabs/Plateform.prefab
  Assets/Prefabs/Player.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/PlayerController.cs
  ProjectSettings/InputManager.asset
  ProjectSettings/TagManager.asset
Labels: New Feature

#2 Feature/sprint
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/PlayerController.cs
  ProjectSettings/InputManager.asset
Labels: New Feature

#4 Feature/dash
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/PlayerController.cs
  ProjectSettings/InputManager.asset
Labels: New Feature

#6 Fix Dash when axisX was 0
  Assets/Prefabs/Player.prefab
  Assets/Scripts/PlayerController.cs
  Packages/packages-lock.json
Labels: bug

#14 Fix velocity behaviour when collisions
  Assets/Scripts/PlayerController2D.cs
  Packages/packages-lock.json
Labels: Improvement, bug
